services:
  api:
    build:
      context: .
      dockerfile: PSSN.Api/Dockerfile
    env_file : .env
    networks:
      - default
    ports:
      - "${REACT_APP_SERVER_PORT}:8081"
    container_name: "${REACT_APP_SERVER_NAME}"
  client:
    build: 
      context: .
      dockerfile: PSSN.Web/Dockerfile
    networks:
      - default
    env_file: .env
    depends_on : 
      - api
    ports:
      - "${REACT_APP_CLIENT_PORT}:80"