// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PSSN.Api.DAL;

#nullable disable

namespace PSSN.Api.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PSSN.Api.DAL.Entities.ConditionalStrategy", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<Guid?>("GenerationResultsGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("generation_results_guid");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int[]>("PatternCoefs")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("pattern_coefs");

                    b.Property<string>("PatternName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pattern_name");

                    b.HasKey("Guid")
                        .HasName("pk_conditional_strategy");

                    b.HasIndex("GenerationResultsGuid")
                        .HasDatabaseName("ix_conditional_strategy_generation_results_guid");

                    b.ToTable("ConditionalStrategy", "scheduled_research");
                });

            modelBuilder.Entity("PSSN.Api.DAL.Entities.GameResults", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<decimal>("CurrentDistribution")
                        .HasColumnType("numeric")
                        .HasColumnName("current_distribution");

                    b.Property<int>("CurrentExperiment")
                        .HasColumnType("integer")
                        .HasColumnName("current_experiment");

                    b.Property<int>("CurrentGeneration")
                        .HasColumnType("integer")
                        .HasColumnName("current_generation");

                    b.Property<Guid>("GenerationResultsGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("generation_results_guid");

                    b.Property<Guid?>("ResearchGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("research_guid");

                    b.HasKey("Guid")
                        .HasName("pk_game_results");

                    b.HasIndex("GenerationResultsGuid")
                        .HasDatabaseName("ix_game_results_generation_results_guid");

                    b.HasIndex("ResearchGuid")
                        .HasDatabaseName("ix_game_results_research_guid");

                    b.ToTable("GameResults", "scheduled_research");
                });

            modelBuilder.Entity("PSSN.Api.DAL.Entities.GenerationResults", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.HasKey("Guid")
                        .HasName("pk_generation_results");

                    b.ToTable("GenerationResults", "scheduled_research");
                });

            modelBuilder.Entity("PSSN.Api.DAL.Entities.GenerationTreeNode", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<Guid?>("GenerationResultsGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("generation_results_guid");

                    b.Property<List<double>>("Results")
                        .IsRequired()
                        .HasColumnType("double precision[]")
                        .HasColumnName("results");

                    b.Property<Guid>("Strategy1Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("strategy1guid");

                    b.Property<Guid>("Strategy2Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("strategy2guid");

                    b.HasKey("Guid")
                        .HasName("pk_generation_tree_node");

                    b.HasIndex("GenerationResultsGuid")
                        .HasDatabaseName("ix_generation_tree_node_generation_results_guid");

                    b.HasIndex("Strategy1Guid")
                        .HasDatabaseName("ix_generation_tree_node_strategy1guid");

                    b.HasIndex("Strategy2Guid")
                        .HasDatabaseName("ix_generation_tree_node_strategy2guid");

                    b.ToTable("GenerationTreeNode", "scheduled_research");
                });

            modelBuilder.Entity("PSSN.Api.DAL.Entities.Research", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<int>("CountOfDistributions")
                        .HasColumnType("integer")
                        .HasColumnName("count_of_distributions");

                    b.Property<int>("CountOfExperiments")
                        .HasColumnType("integer")
                        .HasColumnName("count_of_experiments");

                    b.Property<int>("CrossingCount")
                        .HasColumnType("integer")
                        .HasColumnName("crossing_count");

                    b.Property<decimal>("DistributionStep")
                        .HasColumnType("numeric")
                        .HasColumnName("distribution_step");

                    b.Property<int>("GenCount")
                        .HasColumnType("integer")
                        .HasColumnName("gen_count");

                    b.Property<List<double>>("Ro")
                        .IsRequired()
                        .HasColumnType("double precision[]")
                        .HasColumnName("ro");

                    b.Property<int>("SelectionGroupSize")
                        .HasColumnType("integer")
                        .HasColumnName("selection_group_size");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("StrategiesCount")
                        .HasColumnType("integer")
                        .HasColumnName("strategies_count");

                    b.Property<double>("SwapChance")
                        .HasColumnType("double precision")
                        .HasColumnName("swap_chance");

                    b.Property<int>("TotalGamesCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_games_count");

                    b.HasKey("Guid")
                        .HasName("pk_research");

                    b.ToTable("Research", "scheduled_research");
                });

            modelBuilder.Entity("PSSN.Api.DAL.Entities.ConditionalStrategy", b =>
                {
                    b.HasOne("PSSN.Api.DAL.Entities.GenerationResults", null)
                        .WithMany("Strategies")
                        .HasForeignKey("GenerationResultsGuid")
                        .HasConstraintName("fk_conditional_strategy_generation_results_generation_results_gu");
                });

            modelBuilder.Entity("PSSN.Api.DAL.Entities.GameResults", b =>
                {
                    b.HasOne("PSSN.Api.DAL.Entities.GenerationResults", "GenerationResults")
                        .WithMany()
                        .HasForeignKey("GenerationResultsGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_results_generation_results_generation_results_guid");

                    b.HasOne("PSSN.Api.DAL.Entities.Research", null)
                        .WithMany("GameResults")
                        .HasForeignKey("ResearchGuid")
                        .HasConstraintName("fk_game_results_research_research_guid");

                    b.Navigation("GenerationResults");
                });

            modelBuilder.Entity("PSSN.Api.DAL.Entities.GenerationTreeNode", b =>
                {
                    b.HasOne("PSSN.Api.DAL.Entities.GenerationResults", null)
                        .WithMany("Tree")
                        .HasForeignKey("GenerationResultsGuid")
                        .HasConstraintName("fk_generation_tree_node_generation_results_generation_results_guid");

                    b.HasOne("PSSN.Api.DAL.Entities.ConditionalStrategy", "Strategy1")
                        .WithMany()
                        .HasForeignKey("Strategy1Guid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_generation_tree_node_conditional_strategy_strategy1guid");

                    b.HasOne("PSSN.Api.DAL.Entities.ConditionalStrategy", "Strategy2")
                        .WithMany()
                        .HasForeignKey("Strategy2Guid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_generation_tree_node_conditional_strategy_strategy2guid");

                    b.Navigation("Strategy1");

                    b.Navigation("Strategy2");
                });

            modelBuilder.Entity("PSSN.Api.DAL.Entities.GenerationResults", b =>
                {
                    b.Navigation("Strategies");

                    b.Navigation("Tree");
                });

            modelBuilder.Entity("PSSN.Api.DAL.Entities.Research", b =>
                {
                    b.Navigation("GameResults");
                });
#pragma warning restore 612, 618
        }
    }
}
